name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake
        with:
          github_user_name: sofiebudman
          outputs: github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-animation
          path: github-contribution-grid-snake.svg
      - uses: actions/checkout@v3
      - uses: actions/upload-pages-artifact@v1
        with:
          path: github-contribution-grid-snake.svg
